export default defineEventHandler((event) => {
  return {
    "admin": {"usuario": "admin", "sennha": "1234"},
    "camillafigueiredo": {"usuario": "camillafigueiredo", "sennha": "figueiredo@Ca"},
    "beatrizlopes": {"usuario": "beatrizlopes", "sennha": "lopes@Be"},
    "celiooliveira": {"usuario": "celiooliveira", "sennha": "oliveira@Ce"},
    "rosanaassis": {"usuario": "rosanaassis", "sennha": "assis@Ro"},
    "lauriogarcia": {"usuario": "lauriogarcia", "sennha": "garcia@La"},
    "camilladimas": {"usuario": "camilladimas", "sennha": "dimas@Ca"},
    "luanamello": {"usuario": "luanamello", "sennha": "mello@Lu"},
    "luizsouza": {"usuario": "luizsouza", "sennha": "souza@Lu"},
    "isadorapecanha": {"usuario": "isadorapecanha", "sennha": "pecanha@Is"},
    "nirapimentel": {"usuario": "nirapimentel", "sennha": "pimentel@Ni"},
    "thayanecarvalho": {"usuario": "thayanecarvalho", "sennha": "carvalho@Th"},
    "amandagoncalves": {"usuario": "amandagoncalves", "sennha": "goncalves@Am"},
    "pamelaribeiro": {"usuario": "pamelaribeiro", "sennha": "ribeiro@Pa"},
    "ygorpaixao": {"usuario": "ygorpaixao", "sennha": "paixao@Yg"},
    "rosarodrigues": {"usuario": "rosarodrigues", "sennha": "rodrigues@Ro"},
    "vivianemarques": {"usuario": "vivianemarques", "sennha": "marques@Vi"},
    "vitorgarcia": {"usuario": "vitorgarcia", "sennha": "garcia@Vi"},
    "nailysantana": {"usuario": "nailysantana", "sennha": "santana@Na"},
    "karollinearaujo": {"usuario": "karollinearaujo", "sennha": "araujo@Ka"},
    "cristianosouza": { "usuario": "cristianosouza", "sennha": "souza@Cr"},
    "biancabarcelos": { "usuario": "biancabarcelos", "sennha": "barcelos@Bi"},
  }    
})
