const model = [

    {
        "name": "Thayane",
        "nameFull": "Thayane Carvalho",
        "user": "thayanecarvalho",
        "email": "thayane.carvalhoo@gmailcom",
        "password": "thayane@Th",
        "photo": "https://m.leandrocesar.com/img/thayanecarvalho.jpeg",
        "service": "Consultoria on-line",
        "periodStart": "08/01/24",
        "periodEnd": "08/02/24",
        "status": "Ativo", 
        "target": "Hipertrofia",
        "time": "60 min.",
        "day": "5 dias",
        "workouts": [
                    {
                        "workoutStart": "11/01/24",
                        "workoutEnd": "10/02/24",
                        "workoutAGroups": "Braço/abdomen",
                        "workoutA": [
                            { num: 'Exercício 1', nome: 'Extensora', sets: 3, reps: '7 c/3" + 7', rest: '40"', grupo: '', obs: 'Fazer 7 repetições segurando 3 segundos a cada repetição e + 7 direto no final.', img: 'https: //m.leandrocesar.com/exe/extensora.gif' },
                            { num: 'Exercício 2', nome: 'Agachamento Búlgaro', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Fazer segurandos pesos nas mãos.', img: 'https://m.leandrocesar.com/exe/bulgaro.gif' },
                            { num: 'Exercício 3', nome: 'Agachamento Sumô', sets: 3, reps: '15', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/sumo.gif' },
                            { num: 'Exercício 4', nome: 'Mesa flexora', sets: 3, reps: '10 c/1" + 10"', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/mesaFlexora.gif' },
                            { num: 'Exercício 5', nome: 'Stiff', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Falhando.', img: 'https://m.leandrocesar.com/exe/stiffHBL.gif' },
                            { num: 'Exercício 6', nome: 'Agachamento Smith', sets: 4, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/squatSmith.gif' },
                            { num: 'Exercício 7', nome: 'Abdução de quadril na polia baixa', sets: 3, reps: '12', rest: '40"', grupo: '', obs: 'Segurar 2 segundos a cada repetição.', img: 'https://m.leandrocesar.com/exe/abducaoPolia.gif' },
                            { num: 'Exercício 8', nome: 'Elevação Pélvica', sets: 3, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/elevacaoPelvica.gif' },
                            { num: 'Exercício 9', nome: 'Flexão de quadril (caneleira)', sets: 3, reps: '10', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/flexaoQuadril.gif' },
                            { num: 'Exercício 10', nome: 'Panturrilha aparelho em pé', sets: 2, reps: '20 (2t)', rest: '40"', grupo: '', obs: 'FAzer com 2 tempos a cada repetição.', img: 'https://m.leandrocesar.com/exe/panturrilhaAparelho.gif' }, { num: 'Exercício 10', nome: 'Panturrilha sentada no aparelho', sets: 3, reps: '10 +10" +10', rest: '40"', grupo: '', obs: '', img: 'https: //m.leandrocesar.com/exe/panturrilhaSentado.gif' },
                        ],
                        "cardioB": "Escada",
                        "cardioBTime": "15 minutos",
                        "cardioBDescription": "Fazer 15 minutos de forma constante, que não fique com falta de ar, no ritmo que dê para conversar com alguém, naõ ficar ofegante.",
                        "workoutBGroups": "Braço/abdomen",
                        "workoutB": [
                            { groups: "Braço/abdomen" },
                            { num: 'Exercício 1', nome: 'Extensora', sets: 3, reps: '7 c/3" + 7', rest: '40"', grupo: '', obs: 'Fazer 7 repetições segurando 3 segundos a cada repetição e + 7 direto no final.', img: 'https: //m.leandrocesar.com/exe/extensora.gif' },
                            { num: 'Exercício 2', nome: 'Agachamento Búlgaro', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Fazer segurandos pesos nas mãos.', img: 'https://m.leandrocesar.com/exe/bulgaro.gif' },
                            { num: 'Exercício 3', nome: 'Agachamento Sumô', sets: 3, reps: '15', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/sumo.gif' },
                            { num: 'Exercício 4', nome: 'Mesa flexora', sets: 3, reps: '10 c/1" + 10"', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/mesaFlexora.gif' },
                            { num: 'Exercício 5', nome: 'Stiff', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Falhando.', img: 'https://m.leandrocesar.com/exe/stiffHBL.gif' },
                            { num: 'Exercício 6', nome: 'Agachamento Smith', sets: 4, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/squatSmith.gif' },
                            { num: 'Exercício 7', nome: 'Abdução de quadril na polia baixa', sets: 3, reps: '12', rest: '40"', grupo: '', obs: 'Segurar 2 segundos a cada repetição.', img: 'https://m.leandrocesar.com/exe/abducaoPolia.gif' },
                            { num: 'Exercício 8', nome: 'Elevação Pélvica', sets: 3, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/elevacaoPelvica.gif' },
                            { num: 'Exercício 9', nome: 'Flexão de quadril (caneleira)', sets: 3, reps: '10', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/flexaoQuadril.gif' },
                            { num: 'Exercício 10', nome: 'Panturrilha aparelho em pé', sets: 2, reps: '20 (2t)', rest: '40"', grupo: '', obs: 'FAzer com 2 tempos a cada repetição.', img: 'https://m.leandrocesar.com/exe/panturrilhaAparelho.gif' }, { num: 'Exercício 10', nome: 'Panturrilha sentada no aparelho', sets: 3, reps: '10 +10" +10', rest: '40"', grupo: '', obs: '', img: 'https: //m.leandrocesar.com/exe/panturrilhaSentado.gif' },
                        ],
                        "cardioB": "Escada",
                        "cardioBTime": "15 minutos",
                        "cardioBDescription": "Fazer 15 minutos de forma constante, que não fique com falta de ar, no ritmo que dê para conversar com alguém, naõ ficar ofegante.",
                    },
                    {
                        "workoutStart": "11/02/24",
                        "workoutEnd": "10/03/24",
                        "workoutAGroups": "Braço/abdomen",
                        "workoutA": [
                            { num: 'Exercício 1', nome: 'Extensora', sets: 3, reps: '7 c/3" + 7', rest: '40"', grupo: '', obs: 'Fazer 7 repetições segurando 3 segundos a cada repetição e + 7 direto no final.', img: 'https: //m.leandrocesar.com/exe/extensora.gif' },
                            { num: 'Exercício 2', nome: 'Agachamento Búlgaro', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Fazer segurandos pesos nas mãos.', img: 'https://m.leandrocesar.com/exe/bulgaro.gif' },
                            { num: 'Exercício 3', nome: 'Agachamento Sumô', sets: 3, reps: '15', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/sumo.gif' },
                            { num: 'Exercício 4', nome: 'Mesa flexora', sets: 3, reps: '10 c/1" + 10"', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/mesaFlexora.gif' },
                            { num: 'Exercício 5', nome: 'Stiff', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Falhando.', img: 'https://m.leandrocesar.com/exe/stiffHBL.gif' },
                            { num: 'Exercício 6', nome: 'Agachamento Smith', sets: 4, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/squatSmith.gif' },
                            { num: 'Exercício 7', nome: 'Abdução de quadril na polia baixa', sets: 3, reps: '12', rest: '40"', grupo: '', obs: 'Segurar 2 segundos a cada repetição.', img: 'https://m.leandrocesar.com/exe/abducaoPolia.gif' },
                            { num: 'Exercício 8', nome: 'Elevação Pélvica', sets: 3, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/elevacaoPelvica.gif' },
                            { num: 'Exercício 9', nome: 'Flexão de quadril (caneleira)', sets: 3, reps: '10', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/flexaoQuadril.gif' },
                            { num: 'Exercício 10', nome: 'Panturrilha aparelho em pé', sets: 2, reps: '20 (2t)', rest: '40"', grupo: '', obs: 'FAzer com 2 tempos a cada repetição.', img: 'https://m.leandrocesar.com/exe/panturrilhaAparelho.gif' }, { num: 'Exercício 10', nome: 'Panturrilha sentada no aparelho', sets: 3, reps: '10 +10" +10', rest: '40"', grupo: '', obs: '', img: 'https: //m.leandrocesar.com/exe/panturrilhaSentado.gif' },
                        ],
                        "cardioB": "Escada",
                        "cardioBTime": "15 minutos",
                        "cardioBDescription": "Fazer 15 minutos de forma constante, que não fique com falta de ar, no ritmo que dê para conversar com alguém, naõ ficar ofegante.",
                        "workoutBGroups": "Braço/abdomen",
                        "workoutB": [
                            { groups: "Braço/abdomen" },
                            { num: 'Exercício 1', nome: 'Extensora', sets: 3, reps: '7 c/3" + 7', rest: '40"', grupo: '', obs: 'Fazer 7 repetições segurando 3 segundos a cada repetição e + 7 direto no final.', img: 'https: //m.leandrocesar.com/exe/extensora.gif' },
                            { num: 'Exercício 2', nome: 'Agachamento Búlgaro', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Fazer segurandos pesos nas mãos.', img: 'https://m.leandrocesar.com/exe/bulgaro.gif' },
                            { num: 'Exercício 3', nome: 'Agachamento Sumô', sets: 3, reps: '15', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/sumo.gif' },
                            { num: 'Exercício 4', nome: 'Mesa flexora', sets: 3, reps: '10 c/1" + 10"', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/mesaFlexora.gif' },
                            { num: 'Exercício 5', nome: 'Stiff', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Falhando.', img: 'https://m.leandrocesar.com/exe/stiffHBL.gif' },
                            { num: 'Exercício 6', nome: 'Agachamento Smith', sets: 4, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/squatSmith.gif' },
                            { num: 'Exercício 7', nome: 'Abdução de quadril na polia baixa', sets: 3, reps: '12', rest: '40"', grupo: '', obs: 'Segurar 2 segundos a cada repetição.', img: 'https://m.leandrocesar.com/exe/abducaoPolia.gif' },
                            { num: 'Exercício 8', nome: 'Elevação Pélvica', sets: 3, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/elevacaoPelvica.gif' },
                            { num: 'Exercício 9', nome: 'Flexão de quadril (caneleira)', sets: 3, reps: '10', rest: '40"', grupo: '', obs: '', img: 'https://m.leandrocesar.com/exe/flexaoQuadril.gif' },
                            { num: 'Exercício 10', nome: 'Panturrilha aparelho em pé', sets: 2, reps: '20 (2t)', rest: '40"', grupo: '', obs: 'FAzer com 2 tempos a cada repetição.', img: 'https://m.leandrocesar.com/exe/panturrilhaAparelho.gif' }, { num: 'Exercício 10', nome: 'Panturrilha sentada no aparelho', sets: 3, reps: '10 +10" +10', rest: '40"', grupo: '', obs: '', img: 'https: //m.leandrocesar.com/exe/panturrilhaSentado.gif' },
                        ],
                        "cardioB": "Escada",
                        "cardioBTime": "15 minutos",
                        "cardioBDescription": "Fazer 15 minutos de forma constante, que não fique com falta de ar, no ritmo que dê para conversar com alguém, naõ ficar ofegante.",
                    },
                ],
                "avaliacoes": [
                        {
                            "date": "13/11/2023",
                            "years": 31,
                            "bulk": 61.4,
                            "height": 1.61,
                            "birth": "15/09/1992",
                            "gender": "feminino",
                            "pescoco": 30.5,
                            "ombro": 97,
                            "torax": 84,
                            "toraxRelaxado": 84.5,
                            "toraxContraido": 87.5,
                            "cintura": 71,
                            "abdomen": 79,
                            "quadril": 104.5,
                            // Lado direito
                            "bracoDireitoRelaxado": 26,
                            "bracoDireitoContraido": 27.5,
                            "antebracoDireito": 23,
                            "coxaMedialDireita": 54,
                            "coxaDistalDireita": 49,
                            "pernaDireita": 35.5,
                            // Lado esquerdo
                            "bracoEsquerdoRelaxado": 26,
                            "bracoEsquerdoContraido": 26.5,
                            "antebracoEsquerdo": 22,
                            "coxaMedialEsquerda": 54,
                            "coxaDistalEsquerda": 51,
                            "pernaEsquerda": 37,
                            // Dobras cutâneas,
                            "dtorax": 15,
                            "tricipital": 25,
                            "subEscapular": 34,
                            "axilarMedia": 20,
                            "abdominal": 29,
                            "supraEspinhal": 18,
                            "coxa": 28,
                            "perna": 24,
                            "umero": 5.6,
                            "punho": 4.4,
                            "femur": 9.4,
                            "tornozelo": 6,
                            "flexaoBraco": "--",
                            "flexaoAbdominal": 22
                        }
                    ]
                }
            ]