export default defineEventHandler((event) => {  return [    
  // Série Atual    
  { num: 'Exercício 1', nome: 'Leg press 45', sets: 4, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png' },    
  { num: 'Exercício 2', nome: 'Extensora', sets: 3, reps: '10 +20 curtas', rest: '40"', grupo: '', obs: 'Fazer 10 repetições +20 curtas(da metade para cima).', img: 'https://deepacupuntura.com/img/preImagem.png' },    
  { num: 'Exercício 3', nome: 'mesa flexora', sets: 3, reps: '10 c/1"', rest: '40"', grupo: '', obs: 'Segurar 1 segundo a cada repetição.', img: 'https://deepacupuntura.com/img/preImagem.png' },
  {num: 'Exercício 4', nome: 'Flexão de quadril', sets: 3, reps: '10', rest: '40"', grupo: '', obs: 'Fazer com caneleira.', img: 'https://deepacupuntura.com/img/preImagem.png' },
  {num: 'Exercício 5', nome: 'Agachamento sumô', sets: 3, reps: '12', rest: '40"', grupo: '', obs: 'Segurar um peso bem pesado!', img: 'https://deepacupuntura.com/img/preImagem.png' },
  {num: 'Exercício 6', nome: 'Stiff', sets: 3, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png' },
  {num: 'Exercício 7', nome: 'Abdutora', sets: 3, reps: '15 2T', rest: '40"', grupo: '', obs: 'Fazer 2 tempos a cada repetição.', img: 'https://deepacupuntura.com/img/preImagem.png' },
  {num: 'Exercício 8', nome: 'Adutora', sets: 3, reps: '12 c/1"', rest: '40"', grupo: '', obs: 'Segurar 1 segundo a cada repetição.', img: 'https://deepacupuntura.com/img/preImagem.png' },
  {num: 'Exercício 9', nome: 'Panturrilha em pé (AP)', sets: 3, reps: '20 +curtas', rest: '40"', grupo: '', obs: 'Fazer 20 repetições e no final fazer curtas o máximo que aguentar em cima.', img: 'https://deepacupuntura.com/img/preImagem.png' },
  {num: 'Exercício 10', nome: 'Abdominal aparelho', sets: 3, reps: '12', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png' },
  {num: 'Exercício 11', nome: 'Abdominal remador no solo', sets: 3, reps: '15 a 20', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png' },

    // Modelo:    // { num: 'Exercício 1', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 2', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 3', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 4', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 5', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 6', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 7', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 8', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 9', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 10', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},    // { num: 'Exercício 11', nome: '', sets: 3, reps: '', rest: '40"', grupo: '', obs: '', img: 'https://deepacupuntura.com/img/preImagem.png'},
  ]})